version: '3.7'
services:
    mongodb:
        image: mongo
        container_name: my_mongo
        environment:
            - MONGODB_USER="root" 
            - MONGODB_PASS="LinuxKU13!"
        ports:
            - "27018:27017"
        volumes:
            - "./data/db:/data/db"
        networks:
            - network
        command: [--auth]
        restart: always
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: be_api
        networks:
            - webnet
        ports:
            - 9001:9001
        volumes:
            - "./api:/app"
        restart: always
        networks:
            - network
networks:
   network: